config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'poll/:id' => 'polls#show'

  resources :polls do
    resources :questions
    resources :replies, only: [ :new, :create ]
  end

  root 'polls#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :reply
  belongs_to :question
  belongs_to :possible_answer
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  validates_presence_of :title

  has_many :questions
  has_many :replies

  def serialize_for_graph
    PollSerializer.count_per_month(self).to_json
  end
end

app/models/possible_answer.rb
class PossibleAnswer < ActiveRecord::Base
  belongs_to :question
  has_many :answers
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :poll

  has_many :possible_answers
  has_many :answers
  
  validates :title, :kind, presence: true

  accepts_nested_attributes_for :possible_answers, reject_if: proc { |attributes| attributes['title'].blank? }

  def serialize_for_graph
    PollSerializer.answers_per_question(self).to_json
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :poll
  belongs_to :user
  has_many :answers

  accepts_nested_attributes_for :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  has_many :replies
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def admin!
    authenticate_user!
    redirect_to root_path, alert: "You are not authorized for this operation." unless current_user.admin? || current_user
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :admin!, except: [ :index ]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    if current_user && current_user.admin?
      @pollreplies = @poll.replies
    else
      @pollreplies = @poll.replies.where('user_id=?',current_user.id)
    end
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_poll
  before_action :set_kind_questions
  before_action :admin!

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = @poll.questions.build
    5.times { @question.possible_answers.build }
  end

  def edit
  end

  def create
    @question = @poll.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @poll, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @poll, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :kind, :poll_id, { possible_answers_attributes: [ :title, :check, :question_id ] })
    end

    def set_kind_questions
      @kind_options = [
        [ "Open Answer", "open" ],
        [ "Multiple Choice", "choice" ]
      ]
    end

    def set_poll
      @poll = Poll.find params[:poll_id]
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @poll = Poll.find params[:poll_id]
    @reply = @poll.replies.build

    @poll.questions.each { |question| @reply.answers.build question: question }
  end

  def create
    @poll = Poll.find params[:poll_id]
    @reply = @poll.replies.build reply_params

    if @reply.save
      redirect_to root_path, notice: "Thank you for taking the poll."
    else
      render :new
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:poll_id, :user_id, {
      answers_attributes: [ :value, :question_id, :reply_id, :possible_answer_id ]
      })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    current_user && current_user.admin?
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "CP2M", root_path, class: "navbar-brand"
      / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          =link_to "Polls", polls_path
      %ul.nav.navbar-nav.navbar-right
        -if current_user
          %li
            %span.navbar-text Signed in as #{current_user.email}
            %li
              =link_to destroy_session_path('user'), method: :delete do
                %span.glyphicon.glyphicon-log-out
                Sign out
        -else
          %li
            =link_to new_session_path('user') do
              %span.glyphicon.glyphicon-log-in
              Sign in
          %li
            =link_to new_user_registration_path() do
              %span.glyphicon.glyphicon-pencil
              Sign up

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Poll App - Wykeith (c) 2015
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "https://www.google.com/jsapi"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
  %body
    =render "nav"
    .container
      -flash.each do |name, msg|
        =content_tag :div, msg, :id => "flash_#{name}",class: "flash bg-success" if msg.is_a?(String)
      = yield
    =yield :footer

app/views/layouts/temp.html.haml
- flash.each do |name, msg|
  = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/polls/_form.html.haml
= form_for @poll do |f|
  - if @poll.errors.any?
    #error_explanation
      %h2= "#{pluralize(@poll.errors.count, "error")} prohibited this poll from being saved:"
      %ul
        - @poll.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save', class: "btn btn-default"

app/views/polls/_stats.html.haml
#polls_per_month
  :javascript
    var selector = "#polls_per_month";
    var data = #{@poll.serialize_for_graph};
    Graph.instances.push(new Graph(selector, data, "column"));

#answers_per_question
  -@poll.questions.each do |question|
    -if question.kind == "choice"
      .col-md-6{id: "answer_per_question_#{question.id}" }
      :javascript
        var selector = "#answer_per_question_#{question.id}";
        var data = #{question.serialize_for_graph};
        Graph.instances.push(new Graph(selector, data, "column"));

-content_for :footer do
  :javascript
    google.load('visualization', '1.0', {'packages':['corechart']});
    google.setOnLoadCallback(function () {
      Graph.instances.forEach(function(instance) {
        instance.render();
      });
    });

app/views/polls/edit.html.haml
%h1 Editing poll

= render 'form'

= link_to 'Show', @poll
\|
= link_to 'Back', polls_path
\|
= link_to 'Delete', poll_path, data: {method: 'DELETE'}

app/views/polls/index.html.haml
%h1 Listing polls

%ul
  -@polls.each do |poll|
    %li
      %p
        -if current_user
          =link_to poll.title, poll
        -else
          =poll.title

      %p.btn-group.btn-group-xs
        = link_to 'Edit', poll, class: "btn btn-default" if admin?
        = link_to 'Add question', new_poll_question_path(poll.id), class: "btn btn-default" if admin?
        = link_to 'Delete', poll_path(poll.id), method: :delete, class: "btn btn-default", data: {confirm: 'This will delete all questions in the poll. Are you sure?'} if admin?
        = link_to 'Take Poll', new_poll_reply_path(poll.id), class: "btn btn-default" if current_user

-if admin?
  %p= link_to 'New Poll', new_poll_path, class: "btn btn-primary"

app/views/polls/new.html.haml
%h1 New poll

= render 'form'

= link_to 'Back', polls_path

app/views/polls/show.html.haml
%h1=@poll.title

/ Nav tabs
%ul.nav.nav-tabs
  %li.active
    =link_to "Questions", "#tab-questions", data: { toggle: "tab" }
  %li
    =link_to "Replies", "#tab-replies", data: { toggle: "tab" }
  -if admin?
    %li
      =link_to "Stats", "#tab-stats", data: { toggle: "tab" }
    %li
      =link_to "Results", "#tab-results", data: { toggle: "tab" }

.tab-content
  #tab-questions.tab-pane.active
    %h2 Questions

    %ul
      -@poll.questions.each do |question|
        %li
          %strong=question.title
          =link_to '[Drop]', poll_question_path(@poll, question), method: :delete, class: "btn-xs btn-default" if admin?
          -if question.kind == 'choice'
            %ul
              -question.possible_answers.each do |possible_answer|
                %li
                  -if possible_answer.check? && admin?
                    %span{:class => 'glyphicon glyphicon-ok-circle' }
                  =possible_answer.title
          -else
            %ul This is an Open Question

    %p.btn-group
      = link_to 'Edit Topic', edit_poll_path(@poll), class: "btn btn-default" if admin?
      = link_to 'Add question', new_poll_question_path(@poll), class: "btn btn-default" if admin?
      = link_to 'Take Poll', new_poll_reply_path(@poll), class: "btn btn-default"

  #tab-replies.tab-pane
    %h2 Replies

    -@pollreplies.each do |reply|
      .col-md-6
        .panel.panel-default
          .panel-heading.text-right
            =time_ago_in_words reply.created_at
          .panel-body
            %dl
              -reply.answers.each do |answer|
                %dt{"class" => "text-capitalize"}=truncate(answer.question.try(:title))
                %dd
                  -if answer.question.present?
                    -if !answer.possible_answer.try(:check) && answer.question.try(:kind) == 'choice'
                      %span{:class => 'glyphicon glyphicon-remove alert-danger'}
                    =answer.value.present? ? answer.value : (answer.possible_answer.nil? ? 'No Answer' : answer.possible_answer.try(:title))

  -if admin?
 
    #tab-results.tab-pane
      %h2 All Results
    
      -@poll.questions.each do |question|
        %strong{"class" => "text-capitalize"}
          =question.title
  
        -if question.kind == 'choice'
          -correct_ans = question.answers.joins(:possible_answer).select {|r| r.possible_answer.check}.size
          -total_ans = question.answers.count
          .progress
            .progress-bar.progress-bar-danger{"role" => "progressbar",
            "style" => "text-align:right; width:" + (100-(correct_ans.to_f / total_ans.to_f * 100)).to_s + "%;"}
              %b=total_ans - correct_ans
              Incorrect of
              %b=total_ans
              total replies .
            .progress-bar.progress-bar-info.progress-bar-striped{"role" => "progressbar",
            "style" => "text-align:right; width:" + (correct_ans.to_f / total_ans.to_f * 100).to_s + "%;"}
        -if question.kind == 'open' && !question.nil?
          %small="Open Ended"
          %ol
            -question.answers.each do |answer|
              %li{"class" => "text-lowercase"}
                -if answer.value.empty?
                  No Answer
                -else
                  =answer.value

    #tab-stats.tab-pane
      =render "stats"

app/views/questions/_form.html.haml
= form_for [ @poll, @question ] do |f|
  - if @question.errors.any?
    #error_explanation
      %h3= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      - @question.errors.full_messages.each do |msg|
        =content_tag :div, msg, :id => "Error", class: "flash bg-success"

  %p
    = f.label :title
    = f.text_area :title, class: "form-control"

  %p
    = f.label :kind

  .radio
    -@kind_options.each do |option|
      %label
        =f.radio_button :kind, option[1]
        =option[0]

  %p
    =f.fields_for :possible_answers do |c|
      .form-group
        .input-group
          .input-group-addon
            %strong +
          =c.text_field :title, class: "form-control", placeholder: "Enter a possible answer here"
          .input-group-addon
            %small{:class => "small" } Correct Ans
            =c.check_box :check, :checked => false

  %p
    = f.submit 'Save', class: "btn btn-primary"

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Title
    %th Kind
    %th Poll
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.title
      %td= question.kind
      %td= question.poll
      %td= link_to 'Show', [ @poll, question ]
      %td= link_to 'Edit', edit_poll_question_path(@poll, question)
      %td= link_to 'Destroy', [ @poll, question ], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', @poll

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @question.title
%p
  %b Kind:
  = @question.kind
%p
  %b Poll:
  = @question.poll

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

app/views/replies/_choice.html.haml
%pre=c.label :value, c.object.question.title
-c.object.question.possible_answers.each do |possible_answer|
 %div.radio
  %label
   =c.radio_button :possible_answer_id, possible_answer.id
   =c.hidden_field :question_id
   =possible_answer.title

app/views/replies/_open.html.haml
%pre=c.label :value, c.object.question.title
%p=c.text_area :value, class: "form-control"
=c.hidden_field :question_id

app/views/replies/new.html.haml
%h1=@poll.title

=form_for [ @poll, @reply ] do |f|
  =f.fields_for :answers do |c|
    =render c.object.question.kind, c: c
  %p
    =f.hidden_field :user_id, :value => current_user.try(:id)
    =f.submit "Finish poll", class: "btn btn-primary", id: "form-submit", data: { disable_with: "Please wait..." }